In [1]:
!pip install numpy

In [2]:
import numpy as np

In [ ]:
# Genera un array bidimensional de 4 x 3 con valores aleatorios enteros entre el 34 y el 98. Una vez creado cada array comprueba las dimensiones y los tipos de datos que tenemos en el array

In [96]:
array_bi= np.random.randint(34,99,(4,3))

In [97]:
array_bi

array([[94, 41, 53],
       [97, 35, 83],
       [79, 45, 43],
       [56, 73, 53]])

In [98]:
array_bi.ndim

2

In [99]:
array_bi.dtype

dtype('int64')

In [100]:
# Crea dos arrays (unidimensional, bidimensional) usando el método np.array().


In [101]:
lista1 = [34,56,71,98, 10]
lista2 = [[23,45,89, 56], [12,43,82,44]]

In [102]:
array_unidi= np.array(lista1)
array_unidi

array([34, 56, 71, 98, 10])

In [103]:
array_unidi.ndim

1

In [104]:
array_unidi.dtype

dtype('int64')

In [105]:
array_bidi= np.array(lista2)
array_bi

array([[94, 41, 53],
       [97, 35, 83],
       [79, 45, 43],
       [56, 73, 53]])

In [106]:
array_bidi.ndim

2

In [107]:
array_bidi.dtype

dtype('int64')

In [ ]:
# Crea un array unidimensional con 50 elementos con el método que prefieras y extrae:
#El primer elemento.
#Lo elementos que están en posición impar.
#Los cuatro primeros elementos.
#Los últimos tres elementos.
#Los elementos entre el 4 y el 8 (incluido)

In [108]:
array_uni2= np.arange(0,50,1)

In [109]:
array_uni2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [110]:
array_uni2[0]

0

In [111]:
numeros= []
for i in range(51):
    if i%2!=0:
        num=array_uni2[i]
        numeros.append(num)
array_numeros=np.array(numeros)
array_numeros

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [112]:
array_uni2[:4]

array([0, 1, 2, 3])

In [113]:
array_uni2[-3:]

array([47, 48, 49])

In [114]:
array_uni2[4:9]

array([4, 5, 6, 7, 8])

In [115]:
array_uni2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
#Crea un array de dos dimensiones de 4 x 5 con el método que prefieras y extrae:
#La primera fila y todas las columnas.
#Todas las filas pares.
#La primera columna y todas las filas.

In [116]:
array_bi2= np.random.randint(0,10,(4,5))

In [117]:
array_bi2

array([[8, 7, 3, 7, 1],
       [5, 0, 8, 2, 4],
       [4, 8, 3, 4, 2],
       [9, 2, 8, 7, 4]])

In [118]:
array_bi2[0]

array([8, 7, 3, 7, 1])

In [119]:
numeros2= []
for i in range(4):
    if i%2==0:
        num=array_bi2[i]
        numeros2.append(num)
array_numeros2=np.array(numeros2)
array_numeros2

array([[8, 7, 3, 7, 1],
       [4, 8, 3, 4, 2]])

In [120]:
array_bi2

array([[8, 7, 3, 7, 1],
       [5, 0, 8, 2, 4],
       [4, 8, 3, 4, 2],
       [9, 2, 8, 7, 4]])

In [121]:
def column(matrix, i):
    return [row[i] for row in matrix]

In [122]:
column(array_bi2,0)

[8, 5, 4, 9]